wandb:
  entity: null
#  run_id: askkz9i2
  resume: 'auto'

experiment:
    #project: "training"
    project: "Reproduce_show-O-training"
    name: "show-o-training-stage1"
    output_dir: "show-o-training-stage1"
    max_train_examples_t2i: 40000000
    max_train_examples_mmu: 40000000
    save_every: 5
    eval_every: 2500
    generate_every: 10
    log_every: 2
    log_grad_norm_every: 5
    resume_from_checkpoint: 'latest'

model:
    vq_model:
        type: "magvitv2"
        vq_model_name: "showlab/magvitv2"

    showo:
        load_from_showo: False
        pretrained_model_path: "showlab/show-o"
        w_clip_vit: False
        vocab_size: 58498
        llm_vocab_size: 50295
        #llm_model_path: 'microsoft/phi-1_5'
        llm_model_path: "/home/ubuntu/codespace/llm/Show-o/phi-1_5"
        codebook_size: 8192
        num_vq_tokens: 256
        num_new_special_tokens: 10  # <|soi|> <|eoi|> <|sov|> <|eov|> <|t2i|> <|mmu|> <|t2v|> <|v2v|> <|lvg|> <|pad|>

    gradient_checkpointing: True

dataset:
    gen_type: "imagenet1k"
    und_type: "captioning"
    combined_loader_mode: "max_size_cycle"
    base_path: "/home/ubuntu/codespace/llm/Show-o/datasets/"
    params:
        train_t2i_shards_path_or_url: "datasets/imagenet-1k-samples/train"
        train_mmu_shards_path_or_url: [ "datasets/sa1b/sa_000000.tar/sa_000000.tar" ]
        train_lm_shards_path_or_url: "datasets/falcon-refinedweb/data/train-00000-of*.parquet"
        add_caption_prompt: True
        external_caption_path: "datasets/SAM-LLaVA-Captions10M/sa1b_captions.json"
        external_journeydb_caption_path: ""
        external_laion12m_caption_path: ""
        external_cc12m_caption_path: ""
        validation_prompts_file: "validation_prompts/imagenet_prompts.txt"
        shuffle_buffer_size: 1000
        num_workers: 1
        resolution: 256
        pin_memory: True
        persistent_workers: True

    preprocessing:
        max_seq_length: 128 # for text tokens
        resolution: 256
        center_crop: False
        random_flip: False

optimizer:
    name: adamw
    params: # default adamw params
        learning_rate: 1e-4
        scale_lr: False # scale learning rate by total batch size
        beta1: 0.9
        beta2: 0.999
        weight_decay: 0.01
        epsilon: 1e-8

lr_scheduler:
    scheduler: "cosine"
    params:
        learning_rate: ${optimizer.params.learning_rate}
        warmup_steps: 5

training:
    gradient_accumulation_steps: 1
    noise_type: "mask"
    batch_size_t2i: 1
    batch_size_lm: 1
    batch_size_mmu: 1
    #mixed_precision: "bf16"
    mixed_precision: "fp16"
    enable_tf32: True
    seed: 10086
    max_train_steps: 200
    overfit_one_batch: False
    cond_dropout_prob: 0.1
    min_masking_rate: 0.0
    label_smoothing: 0.0
    max_grad_norm: null
    guidance_scale: 1.5
    generation_timesteps: 12
    t2i_coeff: 1.0
    lm_coeff: 0.1
    mmu_coeff: 1.0
